#!/usr/bin/env bash
# configures nginx to run and listen to port 80

#Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
