#!/usr/bin/env bash

echo "Before sed:"
cat /etc/nginx/sites-enabled/default

# Use sudo to run the sed command with elevated privileges
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

echo "After sed:"
cat /etc/nginx/sites-enabled/default

# Use sudo to run pkill with elevated privileges
sudo pkill -1 nginx

