#!/usr/bin/env bash
# manages the script manage_my_process.
#   when passed the argument `start`:
#     1. starts manage_my_process
#     2. creates a file containings its PID in /var/run/my_process.pid
#     3. displays "manage_my_process started"
#   when passed the argument `stop`:
#     1. stops manage_my_process
#     2. deletes the file /var/run/my_process.pid
#     3. displays "manage_my_process stopped"
#   when passed the argument `restart`:
#     1. stops manage_my_process
#     2. deletes the file /var/run/my_process.pid
#     3. starts manage_my_process
#     4. creates a file containing its PID in /var/run/my_process.pid
#     5. displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
